public class CashierForm extends javax.swing.JFrame {

    
    public CashierForm() {
        initComponents();
    }
    
    ShowForm metafora = new ShowForm();
    String p1n = metafora.getP1n();
    String p1d = metafora.getP1d();
    int p1t = 100;
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtnTheaterA = new javax.swing.JButton();
        jLblShow1 = new javax.swing.JLabel();
        jLbDate1 = new javax.swing.JLabel();
        jBtnPrint1 = new javax.swing.JButton();
        jTxtNumberOfSeats1 = new javax.swing.JTextField();
        jLblFreeTicket1 = new javax.swing.JLabel();
        jLblFreeTicket2 = new javax.swing.JLabel();
        jLbDate5 = new javax.swing.JLabel();
        jLblShow5 = new javax.swing.JLabel();
        jBtnPrint2 = new javax.swing.JButton();
        jTxtNumberOfSeats2 = new javax.swing.JTextField();
        jLblFreeTicket3 = new javax.swing.JLabel();
        jLblFreeTicket4 = new javax.swing.JLabel();
        jBtnTheaterA1 = new javax.swing.JButton();
        jLbDate6 = new javax.swing.JLabel();
        jLblShow6 = new javax.swing.JLabel();
        jBtnPrint3 = new javax.swing.JButton();
        jTxtNumberOfSeats3 = new javax.swing.JTextField();
        jLblFreeTicket5 = new javax.swing.JLabel();
        jLblFreeTicket6 = new javax.swing.JLabel();
        jBtnTheaterA2 = new javax.swing.JButton();
        jLbDate7 = new javax.swing.JLabel();
        jLblShow7 = new javax.swing.JLabel();
        jBtnPrint4 = new javax.swing.JButton();
        jTxtNumberOfSeats4 = new javax.swing.JTextField();
        jLblFreeTicket7 = new javax.swing.JLabel();
        jLblFreeTicket8 = new javax.swing.JLabel();
        jBtnTheaterA3 = new javax.swing.JButton();
        jBtnUpdate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jBtnTheaterA.setText("Theater A");
        jBtnTheaterA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnTheaterAActionPerformed(evt);
            }
        });

        jLblShow1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLbDate1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jBtnPrint1.setText("Print Ticket");
        jBtnPrint1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPrint1ActionPerformed(evt);
            }
        });

        jTxtNumberOfSeats1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTxtNumberOfSeats1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtNumberOfSeats1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtNumberOfSeats1ActionPerformed(evt);
            }
        });

        jLblFreeTicket1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblFreeTicket1.setText("Free");

        jLblFreeTicket2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblFreeTicket2.setText("Seats:");

        jLbDate5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLblShow5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jBtnPrint2.setText("Print Ticket");

        jTxtNumberOfSeats2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTxtNumberOfSeats2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtNumberOfSeats2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtNumberOfSeats2ActionPerformed(evt);
            }
        });

        jLblFreeTicket3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblFreeTicket3.setText("Free");

        jLblFreeTicket4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblFreeTicket4.setText("Seats:");

        jBtnTheaterA1.setText("Theater B");
        jBtnTheaterA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnTheaterA1ActionPerformed(evt);
            }
        });

        jLbDate6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLblShow6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jBtnPrint3.setText("Print Ticket");

        jTxtNumberOfSeats3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTxtNumberOfSeats3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtNumberOfSeats3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtNumberOfSeats3ActionPerformed(evt);
            }
        });

        jLblFreeTicket5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblFreeTicket5.setText("Free");

        jLblFreeTicket6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblFreeTicket6.setText("Seats:");

        jBtnTheaterA2.setText("Theater C");
        jBtnTheaterA2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnTheaterA2ActionPerformed(evt);
            }
        });

        jLbDate7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLblShow7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jBtnPrint4.setText("Print Ticket");

        jTxtNumberOfSeats4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTxtNumberOfSeats4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtNumberOfSeats4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtNumberOfSeats4ActionPerformed(evt);
            }
        });

        jLblFreeTicket7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblFreeTicket7.setText("Free");

        jLblFreeTicket8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblFreeTicket8.setText("Seats:");

        jBtnTheaterA3.setText("Theater D");
        jBtnTheaterA3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnTheaterA3ActionPerformed(evt);
            }
        });

        jBtnUpdate.setText("UPDATE");
        jBtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtnTheaterA3, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLbDate7, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLblFreeTicket8, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLblShow7, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLblFreeTicket7, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTxtNumberOfSeats4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnPrint4, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtnTheaterA2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLbDate6, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLblFreeTicket6, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLblShow6, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLblFreeTicket5, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTxtNumberOfSeats3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnPrint3, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtnTheaterA1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLbDate5, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLblFreeTicket4, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLblShow5, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLblFreeTicket3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTxtNumberOfSeats2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnPrint2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtnTheaterA, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLbDate1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLblFreeTicket2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLblShow1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLblFreeTicket1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTxtNumberOfSeats1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnPrint1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(322, 322, 322)
                        .addComponent(jBtnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(207, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBtnPrint1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblFreeTicket1, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                            .addComponent(jLblShow1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLbDate1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 1, Short.MAX_VALUE)
                                .addComponent(jLblFreeTicket2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jBtnTheaterA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTxtNumberOfSeats1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBtnPrint2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblShow5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLblFreeTicket3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLbDate5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLblFreeTicket4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jBtnTheaterA1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTxtNumberOfSeats2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBtnPrint3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblShow6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLblFreeTicket5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLbDate6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLblFreeTicket6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jBtnTheaterA2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTxtNumberOfSeats3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBtnPrint4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblShow7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLblFreeTicket7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLbDate7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLblFreeTicket8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jBtnTheaterA3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTxtNumberOfSeats4, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jBtnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        jLblFreeTicket1.getAccessibleContext().setAccessibleName("  Free \nTickets:");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnTheaterAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnTheaterAActionPerformed
        
    }//GEN-LAST:event_jBtnTheaterAActionPerformed

    private void jTxtNumberOfSeats1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtNumberOfSeats1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtNumberOfSeats1ActionPerformed

    private void jTxtNumberOfSeats2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtNumberOfSeats2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtNumberOfSeats2ActionPerformed

    private void jBtnTheaterA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnTheaterA1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnTheaterA1ActionPerformed

    private void jTxtNumberOfSeats3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtNumberOfSeats3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtNumberOfSeats3ActionPerformed

    private void jBtnTheaterA2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnTheaterA2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnTheaterA2ActionPerformed

    private void jTxtNumberOfSeats4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtNumberOfSeats4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtNumberOfSeats4ActionPerformed

    private void jBtnTheaterA3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnTheaterA3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnTheaterA3ActionPerformed

    private void jBtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnUpdateActionPerformed
        jLblShow1.setText(p1n);
        jLbDate1.setText(p1d);
        jTxtNumberOfSeats1.setText("" + p1t);
    }//GEN-LAST:event_jBtnUpdateActionPerformed

    private void jBtnPrint1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPrint1ActionPerformed
        jTxtNumberOfSeats1.setText("" + --p1t);
    }//GEN-LAST:event_jBtnPrint1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CashierForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CashierForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CashierForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CashierForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CashierForm().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnPrint1;
    private javax.swing.JButton jBtnPrint2;
    private javax.swing.JButton jBtnPrint3;
    private javax.swing.JButton jBtnPrint4;
    private javax.swing.JButton jBtnTheaterA;
    private javax.swing.JButton jBtnTheaterA1;
    private javax.swing.JButton jBtnTheaterA2;
    private javax.swing.JButton jBtnTheaterA3;
    private javax.swing.JButton jBtnUpdate;
    private javax.swing.JLabel jLbDate1;
    private javax.swing.JLabel jLbDate5;
    private javax.swing.JLabel jLbDate6;
    private javax.swing.JLabel jLbDate7;
    private javax.swing.JLabel jLblFreeTicket1;
    private javax.swing.JLabel jLblFreeTicket2;
    private javax.swing.JLabel jLblFreeTicket3;
    private javax.swing.JLabel jLblFreeTicket4;
    private javax.swing.JLabel jLblFreeTicket5;
    private javax.swing.JLabel jLblFreeTicket6;
    private javax.swing.JLabel jLblFreeTicket7;
    private javax.swing.JLabel jLblFreeTicket8;
    private javax.swing.JLabel jLblShow1;
    private javax.swing.JLabel jLblShow5;
    private javax.swing.JLabel jLblShow6;
    private javax.swing.JLabel jLblShow7;
    private javax.swing.JTextField jTxtNumberOfSeats1;
    private javax.swing.JTextField jTxtNumberOfSeats2;
    private javax.swing.JTextField jTxtNumberOfSeats3;
    private javax.swing.JTextField jTxtNumberOfSeats4;
    // End of variables declaration//GEN-END:variables
}
